# Generated by Django 5.2.5 on 2025-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
